# Generated by Django 3.1.1 on 2023-12-09 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=120)),
                ('lastname', models.CharField(max_length=120)),
                ('DOB', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('fathername', models.CharField(max_length=120)),
                ('fatheroccupation', models.CharField(default='', max_length=120)),
                ('mothername', models.CharField(default='', max_length=120)),
                ('motheroccupation', models.CharField(default='', max_length=120)),
                ('address', models.TextField(default='')),
                ('mark_10', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mark_12', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=120)),
            ],
        ),
    ]
