# Generated by Django 3.1.1 on 2023-12-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_studentdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='password',
            field=models.CharField(default='pass', max_length=150),
        ),
    ]
